// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFlTqZs0B6CiApo8hXIc-CalEHifpTplw',
    appId: '1:893054429893:web:2f4563ac13fbda8f855eac',
    messagingSenderId: '893054429893',
    projectId: 'vitawatch-aa8d2',
    authDomain: 'vitawatch-aa8d2.firebaseapp.com',
    databaseURL: 'https://vitawatch-aa8d2-default-rtdb.firebaseio.com',
    storageBucket: 'vitawatch-aa8d2.firebasestorage.app',
    measurementId: 'G-2CYVNXSQRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKKU52sHk7ht-UHn9HDl_I-dzoF4hdWts',
    appId: '1:893054429893:android:bce2ab6f88187bc4855eac',
    messagingSenderId: '893054429893',
    projectId: 'vitawatch-aa8d2',
    databaseURL: 'https://vitawatch-aa8d2-default-rtdb.firebaseio.com',
    storageBucket: 'vitawatch-aa8d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUlayiEQU0sGs584-RQXNzGuQwParu-Vw',
    appId: '1:893054429893:ios:813dc2037c59c804855eac',
    messagingSenderId: '893054429893',
    projectId: 'vitawatch-aa8d2',
    databaseURL: 'https://vitawatch-aa8d2-default-rtdb.firebaseio.com',
    storageBucket: 'vitawatch-aa8d2.firebasestorage.app',
    iosClientId: '893054429893-n2dm1a5i7afscpuku7olrn7594q0lfjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUlayiEQU0sGs584-RQXNzGuQwParu-Vw',
    appId: '1:893054429893:ios:813dc2037c59c804855eac',
    messagingSenderId: '893054429893',
    projectId: 'vitawatch-aa8d2',
    databaseURL: 'https://vitawatch-aa8d2-default-rtdb.firebaseio.com',
    storageBucket: 'vitawatch-aa8d2.firebasestorage.app',
    iosClientId: '893054429893-n2dm1a5i7afscpuku7olrn7594q0lfjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFlTqZs0B6CiApo8hXIc-CalEHifpTplw',
    appId: '1:893054429893:web:fb233eb5fb172d83855eac',
    messagingSenderId: '893054429893',
    projectId: 'vitawatch-aa8d2',
    authDomain: 'vitawatch-aa8d2.firebaseapp.com',
    databaseURL: 'https://vitawatch-aa8d2-default-rtdb.firebaseio.com',
    storageBucket: 'vitawatch-aa8d2.firebasestorage.app',
    measurementId: 'G-YFYWNG75K7',
  );
}
